### ISSUE TITLE
[Question] Why shutdown is required in cheapo-request example

### ISSUE THREAD

**Issue by WindSoilder** [ProgrammingRust/examples#11]
Hi, firstly very thanks for your awesome examples :-D

I have a little question about this example: https://github.com/ProgrammingRust/examples/blob/master/cheapo-request/src/main.rs#L11

Can you please tell me why this shutdown is required? I have uncomment this line, but it seems that I can never get response from server.

**Comment by jimblandy** [comment]
> Hi, firstly very thanks for your awesome examples :-D

Thanks! I'm glad to hear you're enjoying them!

A TCP connection actually consists of two streams of data: one carrying data from the client to the server, and the other from the server back to the client. As Wikipedia explains, [each side of the connection may be closed independently](https://en.wikipedia.org/wiki/Transmission_Control_Protocol#Connection_termination). When one side closes its sending end, its peer receives end-of-file on the stream (well, end-of-data, really). The connection isn't fully closed until each side has closed the stream it's sending.

In the `cheapo_request` function, the `shutdown(Write)` call closes the client's side of the connection, causing the server to receive an end-of-file. This seems to be necessary to get a response from the servers I tried.

However, I wasn't able to find a good explanation of why it's necessary. [RFC 1945](https://datatracker.ietf.org/doc/html/rfc1945#section-7.2.2) explains:

> Closing the connection cannot be used to indicate the end of a request body, since it leaves no possibility for the server to send back a response. Therefore, HTTP/1.0 requests containing an entity body must include a valid Content-Length header field.

This text is confusing to me, because it doesn't seem to understand TCP's behavior that I just explained above: it's perfectly possible for the client to close its side of the connection, while still keeping the incoming side open to receive the server's response. But, whatever's going on there, from the RFC we can assume that the server is not actually using end-of-file to decide whether our request has been fully received.

I suspect the reason the `shutdown(Write)` is necessary is that, by default, the kernel doesn't actually transmit data on a TCP stream the instant you write to the socket. If you only write a little bit of data, the kernel actually waits around for a fraction of a second before transmitting it, to see if you're going to write any more, so it can coalesce several of your writes into a single large packet, rather than sending lots of tiny packets. This is called [Nagle's algorithm](https://en.wikipedia.org/wiki/Nagle%27s_algorithm). The effect of our shutdown is to tell the kernel that there's no more data on the way, and it should go ahead and transmit the request, small as it is, immediately. Modern servers have very short timeouts, to frustrate denial-of-service attacks, and perhaps the Nagle delay is long enough that the server will time out and drop the connection before the Nagle algorithm gets around to sending our request!

In any case, you can see why I decided to simply present the code that works without getting into these details. I considered just presenting it as a custom protocol, not HTTP, but since it does seem to roughly work, I thought it might be nice to help people see that HTTP is not so impossible to understand: you just send this text, and (maybe) you get a reply!

In any case, I hope the lack of an explanation for the `shutdown` call wasn't too distracting from the point of the chapter.
